"""
Django settings for pro_cli project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/


"""



from pathlib import Path
from turtle import circle
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5%4zi0@cb!+tc+j2jrh@6ya#g7af$s!^y)ln#hhfygln8di!c-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "192.168.1.111",
    "localhost",
    "127.0.0.1"
    
    ]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'comptes.apps.ComptesConfig',
    'rendez_vous.apps.RendezVousConfig',
    'dossier_medical.apps.DossierMedicalConfig',
    'consultations.apps.ConsultationsConfig',
    'prescriptions.apps.PrescriptionsConfig',
    'facturations.apps.FacturationsConfig',
    'paiements.apps.PaiementsConfig',
    'departement.apps.DepartementConfig',
    'patient.apps.PatientConfig',
    'medecin.apps.MedecinConfig',
    'corsheaders',

    'rest_framework',
    'django_filters',
    'celery',
    'django_celery_beat',
]


REST_FRAMEWORK = {

    # AUTHENTIFICATION
    "DEFAULT_AUTHENTICATION_CLASSES": [

         'rest_framework_simplejwt.authentication.JWTAuthentication',

     ],

    #  PERMISSIONS
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],

    # FILTRES
    "DEFAULT_FILTER_BACKENDS": [

        'django_filters.rest_framework.DjangoFilterBackend',

        'rest_framework.filters.SearchFilter',

        'rest_framework.filters.OrderingFilter',

    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pro_cli.urls'




AUTHENTICATION_BACKENDS = [
    'comptes.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# JAZZMIN_SETTINGS = {
#     "site_title": "ProCli Admin",
#     "site_header": "ProCli Administration",
#     "site_brand": "ProCli",
#     "welcome_sign": "Bienvenue sur le panneau d'administration de ProCli",
#     "copyright": "ProCli © 2024",
#     "show_ui_builder": True,
#     "show_sidebar": True,
#     "site_logo_classes": "img-circle",
    
#     "sidebar_classes": "bg-dark",

# }

# JAZZMIN_UI_TWEAKS = {
    
#     "theme": "simplex",
    
# }

STATICFILES_DIRS = [
    BASE_DIR / "static"
]


WSGI_APPLICATION = 'pro_cli.wsgi.application'




CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'rpc://'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'



# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


LOGIN_REDIRECT_URL='comptes:dashboard'
LOGIN_URL = 'comptes:login'
LOGOUT_URL = 'comptes:logout'




CELERY_BEAT_SCHEDULE = {
    'send-rdv-reminders': {
        'task': 'rendez_vous.tasks.notify_upcoming_appointments_batch',
        'schedule': 86400.0,  # 1 fois par jour
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
