# Generated by Django 6.0.1 on 2026-06-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0002_medecin_nom'),
        ('patient', '0001_initial'),
        ('rendez_vous', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['-date', '-heure']},
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['date'], name='rendez_vous_date_e74afe_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['medecin'], name='rendez_vous_medecin_b079f0_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['patient'], name='rendez_vous_patient_ca1a8f_idx'),
        ),
    ]
