# Generated by Django 6.0.1 on 2026-06-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-date_prescription'], 'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.AddIndex(
            model_name='itemsprescription',
            index=models.Index(fields=['prescription'], name='prescriptio_prescri_92f86f_idx'),
        ),
    ]
