# Generated by Django 6.0.1 on 2026-06-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='nom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
