# Generated by Django 6.0.1 on 2026-05-23 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecin', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('payee', models.BooleanField(default=False)),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='medecin.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='patient.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DetailFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medicament', models.CharField(max_length=250)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_facture', to='facturations.facture')),
            ],
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['patient', 'payee'], name='facturation_patient_c6a7e3_idx'),
        ),
    ]
